spring.application.name=backend

# PostgreSQL Database Connection Setup
spring.datasource.url=jdbc:postgresql://localhost:5432/setusathi_db
spring.datasource.username=postgres
spring.datasource.password=your_postgreSql_Password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA & Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

